# Generated by Django 4.2.6 on 2023-10-18 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='full_name',
            field=models.CharField(default=datetime.datetime(2023, 10, 18, 9, 59, 10, 9778, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
