# Generated by Django 4.2.6 on 2023-10-18 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_leave_request_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='file',
            field=models.FileField(default=datetime.datetime(2023, 10, 18, 13, 59, 30, 45030, tzinfo=datetime.timezone.utc), upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
