# Generated by Django 4.2.6 on 2023-10-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_leave_request_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_request',
            old_name='from_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leave_request',
            old_name='to_date',
            new_name='start_date',
        ),
    ]
