# Generated by Django 4.2.6 on 2023-10-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_from_date_leave_request_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
