# Generated by Django 4.2.6 on 2023-10-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_leave_request_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
