# Generated by Django 4.2.6 on 2023-10-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_leave_request_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='casual_leave_entitlement',
            field=models.IntegerField(default=24),
        ),
    ]
