# Generated by Django 4.2.6 on 2023-11-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_employee_casual_leave_entitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
