# Generated by Django 4.2.6 on 2023-11-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_leave_request_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='casual_leave_entitlement',
            field=models.IntegerField(default=10),
        ),
    ]
